repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
    args: ['--unsafe']
  - id: end-of-file-fixer
    exclude: .*\.ipynb
  - id: trailing-whitespace

- repo: https://github.com/kynan/nbstripout
  rev: 0.6.1
  hooks:
    - id: nbstripout

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.3.0
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
