site_name: PassengerSim
theme:
  name: material
  custom_dir: docs/.overrides
  icon:
    logo: material/seat-recline-extra
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.indexes
    - navigation.prune

extra_css:
  - stylesheets/extra.css

plugins:
  - offline
  - autorefs
  - mkdocs-jupyter:
      include: ["*.nbconvert.ipynb", "*.ipynb"]
      execute: false
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: false
            docstring_style: numpy
            allow_inspection: false
            docstring_section_style: list
            show_if_no_docstring: true
            load_external_modules: false
  - search
  - gen-files:
      scripts:
      - docs/.scripts/_generate_ref_pages.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details

repo_url: https://github.com/PassengerSim/passengersim
repo_name: PassengerSim/passengersim

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  # TODO: https://github.com/lukasgeiter/mkdocs-awesome-pages-plugin
  - index.md
  - User Guide:
    - Installation: 'user-guide/installation.md'
    - How it Works: user-guide/how-it-works.md
    - RM Systems: user-guide/rm-systems.md
    - Writing Configs: user-guide/writing-configs.md
  - Tutorials:
    - Tutorials/index.md
    - Tutorials/reading-data.ipynb
    - Tutorials/demo-3mkt.nbconvert.ipynb  
    - Tutorials/demo-3mkt-db.nbconvert.ipynb
  - API:
    - API/index.md
    - Config:
      - API/config/00-configs.md
      - API/config/01-simulation-controls.md
      - API/config/airlines.md
      - API/config/booking_curves.md
      - API/config/choice_model.md
      - API/config/database.md
      - API/config/demands.md
      - API/config/fares.md
      - API/config/legs.md
      - API/config/named.md
      - API/config/paths.md
      - API/config/rm_steps.md
      - API/config/rm_systems.md
      - API/config/snapshot_filter.md
    - Core:
      - API/Core/index.md
      - API/Core/00-SimulationEngine.md
      - API/Core/Airline.md
      - API/Core/BookingCurves.md
      - API/Core/Bucket.md
      - API/Core/ChoiceModel.md
      - API/Core/Demand.md
      - API/Core/Fare.md
      - API/Core/Generator.md
      - API/Core/Leg.md
      - API/Core/Path.md
      - API/Core/PathClass.md