site_name: AirSim
theme:
  name: material
  icon:
    logo: material/shield-airplane
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs

extra_css:
  - stylesheets/extra.css

plugins:
  - offline
  - mkdocs-jupyter:
      execute: true
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: false
            docstring_style: numpy
            allow_inspection: false
            docstring_section_style: list
            show_if_no_docstring: true
            load_external_modules: false
  - search
  - gen-files:
      scripts:
      - docs/.scripts/_generate_ref_pages.py

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

repo_url: https://github.com/jpn--/SimByWire
repo_name: jpn--/sim-by-wire
