# pyproject.toml
[build-system]
requires = [
    "setuptools",
    "wheel",
    "setuptools_scm[toml]>=7.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
fallback_version = "0.1.0"
write_to = "bywire/_version.py"

[project]
name = "bywire"
dynamic = ["version"]
requires-python = ">=3.11"
dependencies = [
    "numpy",
    "scipy",
    "pandas",
    "pydantic>=2.0",
]

[tool.setuptools]
packages = ["bywire"]

[metadata]
description = "User interface for AirSim"
author = "Atlanta Analytics LLC"
author_email = "jeff@newman.me"
